# Generated by Django 3.1 on 2020-08-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titre_wiki', '0003_auto_20200808_1714'),
        ('article_wiki', '0002_auto_20200808_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlewiki',
            name='titre_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='titre_wiki.titrewiki'),
            preserve_default=False,
        ),
    ]
