# Generated by Django 3.1 on 2020-08-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_wiki', '0004_auto_20200808_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlewiki',
            old_name='titre_id',
            new_name='titre',
        ),
    ]
