# Generated by Django 3.1 on 2020-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titre_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTitle',
            new_name='WikiArticleTitle',
        ),
    ]
