# Generated by Django 3.1 on 2020-08-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titre_wiki', '0002_auto_20200807_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiArticleTitle',
            new_name='TitreWiki',
        ),
        migrations.AlterModelTable(
            name='titrewiki',
            table='titre_wiki',
        ),
    ]
